### ISSUE TITLE
Remove "specification draft"

### ISSUE THREAD

**Issue by dgarijo** [TEC-Toolkit/ECFO#11]
Now they are releases

**Comment by inaja** [comment]
I am editing the files for the w3id site, I will remove the specification draft. but the 'this' instances referring to our affiliations are showing up with the other instances. Do I just remove them manually myself ?

**Comment by dgarijo** [comment]
Please do not remove "this" from instances, because that's a good practice.

The specification draft is a label that can be changed in the html. Please
change it to just "TEC Toolkit specification"

**Comment by inaja** [comment]
OK I wont remove the this,  but the websites of the universities are showing up in Table 1 (Namespaces used in the document)

**Comment by dgarijo** [comment]
Ah they can be removed from there indeed. I thought you meant in the
ontology

**Comment by inaja** [comment]
Also, just for clarification... I didnt mean to remove the 'this' from the ontology itself, I meant to remove the 'this' from the section of the instances in the w3id website. but if it is good practice then i wont touch the instances section of the website code

**Comment by dgarijo** [comment]
They are correct in that section. The instances include "#this" because the
url sof the respective institutions are not technically entities

**Comment by stefanogermano** [comment]
I think there was a misunderstanding on this.
We discussed it during our meeting on Tuesday.

PECO:
![image](https://user-images.githubusercontent.com/2128484/236291199-3ef74c03-7619-45e4-a456-29482f531237.png)

ECFO:
![image](https://user-images.githubusercontent.com/2128484/236291321-5342f71f-3a28-43ac-a67f-d8597f408d06.png)

It is easy to see that there is something wrong (at least in one of them).
This should be fixed.

**Comment by dgarijo** [comment]
Why did this happen :D

**Comment by dgarijo** [comment]
This was due to wrong annotations in the instances. I changed them
