### ISSUE TITLE
Logo breaks in the documentation and ontology

### ISSUE THREAD

**Issue by dgarijo** [TEC-Toolkit/ECFO#24]
@stefanogermano 
This commit: https://github.com/TEC-Toolkit/ECFO/commit/f52b328b41147eb58126aecce8eef3badbb3a1a9
Breaks the ontology logo in the documentation https://tec-toolkit.github.io/ECFO/release/1.0.0/index-en.html and the ontology

**Comment by dgarijo** [comment]
Fixed

**Comment by stefanogermano** [comment]
Thanks
