### ISSUE TITLE
dc:publisher and rdf:value  missing in documentation v 0.0.1

### ISSUE THREAD

**Issue by m-markovic** [TEC-Toolkit/ECFO#4]
The HTML documentation doesn't include dc:publisher (object property) and rdf:value (data property)

**Comment by dgarijo** [comment]
I know. Who is the publisher of the ontology?

**Comment by stefanogermano** [comment]
any updates on this?

**Comment by dgarijo** [comment]
No, I need to add it. I will work on it for version 1.0.0

**Comment by dgarijo** [comment]
Done
