### ISSUE TITLE
use qudt:symbol instead of rdfs:label for symbols of ecfo:ChemicalCompound

### ISSUE THREAD

**Issue by m-markovic** [TEC-Toolkit/ECFO#7]
ecfo:ChemicalCompound should be described by rdfs:label where long name is available (e.g., carbon dioxide) and qudt:symbol should be used to link a literal describing the symbol (e.g., CO2)

**Comment by dgarijo** [comment]
It should be "chemical formula". As you well indicated, symbol is more for units.

**Comment by dgarijo** [comment]
Separating the issue in two
