### ISSUE TITLE
Add ontology diagrams

### ISSUE THREAD

**Issue by dgarijo** [TEC-Toolkit/ECFO#9]
We are missing hand made diagrams to illustrate the doc!

**Comment by stefanogermano** [comment]
I offered to draw them at our last meeting, but I am waiting for the latest (stable) version of the ontology (in the doc https://w3id.org/ecfo).

**Comment by dgarijo** [comment]
I think the ontology is final except for two missing data properties.
Please go ahead and we'll add the missing props later

**Comment by stefanogermano** [comment]
Addressing it in private.

**Comment by dgarijo** [comment]
Sorry, the issue is still unaddressed. Let's close it when we have the diagrams in the doc :)

**Comment by dgarijo** [comment]
Fixed in https://github.com/TEC-Toolkit/ECFO/pull/19
